### ISSUE TITLE
Import BMs in browser defaults to "Other Bookmarks" once synced

### ISSUE THREAD

**Issue by kayceegb** [Offerel/SyncMarks-Webapp#33] opened 2020-12-02 17:36 UTC
Hi,

Another one. 
From a clean start point (remove everything from bookmarks and export to addon).
Restore a bookmark backup. 
At webapp bookmarks are all in "Other Bookmarks" and do not respect original hierarchy. 

K.

**Comment by kayceegb** [comment] 2020-12-02 17:44
I investigated at this one too. 

After the change below, bookmarks are added in correct folder. 

```
diff --git a/index.php b/index.php
index 500db7b..ba7fb6c 100644
--- a/index.php
+++ b/index.php
@@ -967,7 +967,7 @@ function addBookmark($database, $ud, $bm) {
                }
        }
        e_log(8,"Get folder data for adding bookmark");
-       $query = "SELECT MAX(`bmIndex`) +1 AS `nindex`, `bmParentId` FROM `bookmarks` WHERE `bmParentId` IN (SELECT `bmId` FROM `bookmarks` WHERE `bmType` = 'folder' AND `bmTitle` = '".$bm['nfolder']."' AND `userId` = ".$ud['userID'].")";
+       $query = "SELECT COALESCE(MAX(`bmIndex`) +1, 0) AS `nindex`, COALESCE(`bmParentId`,'".$bm['folder']."') AS `bmParentID` FROM `bookmarks` WHERE `bmParentId` = '".$bm['folder']."' AND `userId` = ".$ud['userID'].";";
        $statement = $db->prepare($query);
        e_log(9,$query);
        $statement->execute();
```

As it was for folder creation, MAX bmIndex and bmParentID in this situation are NULL, so we have to force an initial value.

**Comment by Offerel** [comment] 2020-12-02 20:39
I can't reproduce the issue with restoring the bookmarks. At least here, i can export and import without loosing any bookmarks or folders.

**Comment by kayceegb** [comment] 2020-12-02 22:31
Sorry I corrected the first post. The problem is not at addon but webapp. 

This is the initial state. 
![screen-2020-12-02-23-21-42 jpg](https://user-images.githubusercontent.com/59441547/100938682-6e793080-34f5-11eb-8637-13e27b3b839b.png)

Once restored the bookmarks look like this. 
![screen-2020-12-02-23-22-49 jpg](https://user-images.githubusercontent.com/59441547/100938696-7638d500-34f5-11eb-9c15-3a5bab60f7b1.png)

Look at the difference. In FF it's ok. In webapp, BMs are restored at wrong place.

**Comment by Offerel** [comment] 2020-12-03 06:34
IF you restore the bookmarks in the browser, the browser receives all bookmarks as one request together. Then it removes all webapp listeners during import and restore the bookmarks. When this operations are completed, the listeners will re-added. There should be no operation on webapp backend during the restore, a least not from this addon. 

I can only imagine, that there is maybe another addon active, which interacts bookmarks or the browser internal sync is doing something after the import is finalized, which triggers a bookmark move operation. I have never seen such a behavior before. At lease here, i use FF-Sync and my addon in parallel without any issue.

Moving an bookmark in webapp is a separate process, triggered by a single manual move or triggered by the addon, when the browser triggers a move. All these triggers are offline during an import.

**Comment by kayceegb** [comment] 2020-12-03 12:13
I don't know the internals, but I don't see exactly what you say. 

To prevent interferences from precedent tests, I restarted with a clean/new/fresh profile. Then what I have done:

- install addon as a temporary addon
- configure it to use php mode with all sync actions activated
- in addon click save to validate credentials
- in addon click remove to remove all bookmarks
- in addon click export to be in synced state between browser and webapp
- in browser open library, then "Import and backup", restore and I select a previous backup
- validate replace all bookmarks

Then I see bookmarks appear in bookmarks toolbar, and the communication with webapp starts. 

In browser's toolbar the restore is ok, in webapp's side the bookmarks are not in the correct folder.

**Comment by Offerel** [comment] 2020-12-03 13:14
When you say "in browser open library, then "Import and backup", restore and I select a previous backup", you mean that you use the internal restore function from FF? 

In that case, i cant do much against that. This is an internal function of Firefox and cant controlled by the addon. I know that there are triggers internally in Firefox which starts and stops all bookmark api related triggers. For my understanding such operations should be stopped by start of an import process and resumed, when this process ends. If thats not the case, i assume this is a bug in firefox or by design. The only thing you can do is to deactivate the addon or the options during this process.

**Comment by kayceegb** [comment] 2020-12-03 13:38
Exactly, this is the internal function from FF. 

In my point of view, what we see and what is done on browser's side is not the problem. Like I said the request send by addon is completely correct. 

In addition, I am able to trigger the problem in a different manner. 

- install addon as a temporary addon
- configure it to use php mode with all sync actions activated
- in addon, click save to validate credentials
- in addon, click remove to remove all bookmarks
- in addon, click export to be in synced state between browser and webapp
- in browser, open a url in a tab
- in browser, right click on the above tab then select bookmark tab and validate. This defaults to folder "Bookmarks Menu". 

On browser's side the bookmark is in "Bookmarks Menu". In webapp, it ends in "Other Bookmarks". 

So, where is the bug ? 

You said above you have tested. Have you tried to reproduce all this with empty bookmarks on browser's side before export?

**Comment by Offerel** [comment] 2020-12-04 12:58
I tried your example but couldn't reproduce that completely. Normally the browser has no default bookmark folder, instead of this, it makes use of the last selected folder. It also makes a difference, how you add a bookmark, at least with Firefox. FF behaves different, if you use Ctrl+D, click in menu "Add bookmark" or rightclick in the tab. For the addon, this makes no difference. The addon sends the folder where to create the bookmark along with the bookmark itself.

But it seems there was an error in of the last commits, to identify the correct folder at the backend. I have fixed this now. I will make a new commit maybe today or tomorrow.

**Comment by kayceegb** [comment] 2020-12-04 14:14
In the meanwhile I had some progress too. 

Inspecting carrefully what hapens, it seems that even adding a bookmark, in the above initial situation,  with ctrl-d, there is a problem. 

```
==> /var/log/bookmark.log <==
[04-Dec-2020 13:52:30] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT * FROM `users` WHERE `userName`='admin@shared.ff'
[04-Dec-2020 13:52:31] - [notice] - admin@shared.ff - 127.0.0.1 - Get userdata from the database
[04-Dec-2020 13:52:31] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT * FROM `users` WHERE `userName`='admin@shared.ff'
[04-Dec-2020 13:52:31] - [notice] - admin@shared.ff - 127.0.0.1 - Try to add folder 'GitHub - Offerel/SyncMarks-Extension: Firefox AddOn to share bookmarks across WebDAV Shares'
[04-Dec-2020 13:52:31] - [debug] - admin@shared.ff - 127.0.0.1 - {"id":"7rjzzkH_Rq8a","url":"https://github.com/Offerel/SyncMarks-Extension","title":"GitHub - Offerel/SyncMarks-Extension: Firefox AddOn to share bookmarks across WebDAV Shares","type":"bookmark","folder":"unfiled_____","nfolder":"Other Bookmarks","added":1607089949983}
[04-Dec-2020 13:52:31] - [notice] - admin@shared.ff - 127.0.0.1 - Check if bookmark already exists for user.
[04-Dec-2020 13:52:31] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT COUNT(*) AS bmcount, MAX(bmAction) as bmaction FROM `bookmarks` WHERE `bmUrl` = 'https://github.com/Offerel/SyncMarks-Extension' and userID = 1
[04-Dec-2020 13:52:31] - [notice] - admin@shared.ff - 127.0.0.1 - Get folder data for adding bookmark
[04-Dec-2020 13:52:31] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT MAX(`bmIndex`) +1 AS `nindex`, `bmParentId` FROM `bookmarks` WHERE `bmParentId` IN (SELECT `bmId` FROM `bookmarks` WHERE `bmType` = 'folder' AND `bmTitle` = 'Other Bookmarks' AND `userId` = 1)
[04-Dec-2020 13:52:31] - [notice] - admin@shared.ff - 127.0.0.1 - Folder not found, using 'unfiled_____'.
[04-Dec-2020 13:52:31] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT MAX(`bmIndex`) +1 AS `nindex`, `bmParentId` FROM `bookmarks` WHERE `userId` = 1
[04-Dec-2020 13:52:31] - [notice] - admin@shared.ff - 127.0.0.1 - Add bookmark 'GitHub - Offerel/SyncMarks-Extension: Firefox AddOn to share bookmarks across WebDAV Shares'
[04-Dec-2020 13:52:31] - [debug] - admin@shared.ff - 127.0.0.1 - INSERT INTO `bookmarks` (`bmID`,`bmParentID`,`bmIndex`,`bmTitle`,`bmType`,`bmURL`,`bmAdded`,`userID`) VALUES ('7rjzzkH_Rq8a', 'unfiled_____', 5, 'GitHub - Offerel/SyncMarks-Extension: Firefox AddOn to share bookmarks across WebDAV Shares', 'bookmark', 'https://github.com/Offerel/SyncMarks-Extension', 1607089949983, 1)
```

As you can see, the parent folder is not found, and that fallbacks to "unfiled". It is because the request select MAX don't find anything and returns null for both
```
sqlite> SELECT MAX(`bmIndex`) +1 AS `nindex`, `bmParentId` FROM `bookmarks` WHERE `bmParentId` IN (SELECT `bmId` FROM `bookmarks` WHERE `bmType` = 'folder' AND `bmTitle` = 'Other Bookmarks' AND `userId` = 1);
nindex          bmParentID  
--------------  ------------
                            
changes:   1   total_changes: 15
```

That was already the case for folder creation in the same situation. 
To help in that case, I reused the change I provided above with less modification, and to be coeherent with what you put in the fix for folder, with this it's a lot better:
```
diff --git a/index.php b/index.php
index 500db7b..9a88f65 100644
--- a/index.php
+++ b/index.php
@@ -967,7 +967,7 @@ function addBookmark($database, $ud, $bm) {
        }
    }
    e_log(8,"Get folder data for adding bookmark");
-   $query = "SELECT MAX(`bmIndex`) +1 AS `nindex`, `bmParentId` FROM `bookmarks` WHERE `bmParentId` IN (SELECT `bmId` FROM `bookmarks` WHERE `bmType` = 'folder' AND `bmTitle` = '".$bm['nfolder']."' AND `userId` = ".$ud['userID'].")";
+   $query = "SELECT IFNULL(MAX(`bmIndex`) +1,0) AS `nindex`, IFNULL(`bmParentId`, '".$bm['folder']."') AS `bmParentID` FROM `bookmarks` WHERE `bmParentId` IN (SELECT `bmId` FROM `bookmarks` WHERE `bmType` = 'folder' AND `bmTitle` = '".$bm['nfolder']."' AND `userId` = ".$ud['userID'].")";
    $statement = $db->prepare($query);
    e_log(9,$query);
    $statement->execute();
```

It fixes the situation for ctrl-d, right click on tab then "bookmark tab". The last one I am not sur which one you are talking about. 
And it even helps in the initial issue, for importing BMs. 

But you said there may be an error in last commits. Do you have any idea of the culprit ? Or maybe do you remember the last correct one ?

**Comment by Offerel** [comment] 2020-12-08 13:03
Fixed in one  of the last commits

**Closed by Offerel** 2020-12-08 13:03 UTC

**Comment by kayceegb** [comment] 2020-12-08 13:23
Actually, no this not fixed
```
[08-Dec-2020 13:18:29] - [notice] - admin@shared.ff - 127.0.0.1 - Get folder data for adding bookmark
[08-Dec-2020 13:18:29] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT IFNULL(MAX(`bmIndex`),-1) + 1 AS `nindex`, `bmID` FROM `bookmarks` WHERE `userID` = 1 AND `bmID` IN (SELECT `bmId` FROM `bookmarks` WHERE `bmType` = 'folder' AND `bmTitle` = 'Lesezeichen-Menü' AND `userId` = 1);
[08-Dec-2020 13:18:29] - [notice] - admin@shared.ff - 127.0.0.1 - Folder not found, using 'unfiled_____'.
[08-Dec-2020 13:18:29] - [debug] - admin@shared.ff - 127.0.0.1 - SELECT MAX(`bmIndex`) +1 AS `nindex`, `bmParentId` FROM `bookmarks` WHERE `userId` = 1;
[08-Dec-2020 13:18:29] - [notice] - admin@shared.ff - 127.0.0.1 - Add bookmark 'Issues · Offerel/SyncMarks-Webapp · GitHub'
[08-Dec-2020 13:18:29] - [notice] - admin@shared.ff - 127.0.0.1 - Undefined index: bmID in /var/www/html/bmsync/index.php on line 998
[08-Dec-2020 13:18:29] - [debug] - admin@shared.ff - 127.0.0.1 - INSERT INTO `bookmarks` (`bmID`,`bmParentID`,`bmIndex`,`bmTitle`,`bmType`,`bmURL`,`bmAdded`,`userID`) VALUES ('ozDmP2xyHfKQ', '', 7, 'Issues · Offerel/SyncMarks-Webapp · GitHub', 'bookmark', 'https://github.com/Offerel/SyncMarks-Webapp/issues?q=is:issuesort:updated-descis:open', 1607373990382, 1)
```

And in webapp, it's horrible

**Comment by kayceegb** [comment] 2020-12-09 13:38
That's better with yesterday's latest changes. Importing backups or creating bookmarks ends in correct folder(s). But there is a gap.
